// angular/src/app/components/score-board.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-score-board',
  standalone: true,
  template: `
    <div class="flex items-baseline gap-2 p-2 bg-gray-200 rounded-lg shadow">
      <span class="font-bold">{{ kyokuLabel }}</span>
      <span class="text-sm">残り{{ wallCount }}</span>
      <span class="text-sm">{{ honba }}本場</span>
      <span class="text-sm flex items-center">
        供託
        <span data-testid="kyotaku" class="ml-1">{{ kyotaku }}</span>
      </span>
    </div>
  `,
})
export class ScoreBoardComponent {
  @Input({ required: true }) kyoku = 1;
  @Input({ required: true }) wallCount = 0;
  @Input({ required: true }) kyotaku = 0;
  @Input({ required: true }) honba = 0;

  get kyokuLabel(): string {
    const labels = ['東1局', '東2局', '東3局', '東4局', '南1局', '南2局', '南3局', '南4局'];
    return labels[this.kyoku - 1] || '';
  }
}

// src/components/ScoreBoard.tsx
import React from 'react';
interface ScoreBoardProps {
  kyoku: number;
  wallCount: number;
  kyotaku: number;
  honba: number;
}

export const ScoreBoard: React.FC<ScoreBoardProps> = ({
  kyoku,
  wallCount,
  kyotaku,
  honba,
}) => {
  const kyokuStr = ['東1局', '東2局', '東3局', '東4局', '南1局', '南2局', '南3局', '南4局'][kyoku - 1] || '';
  return (
    <div
      className="flex items-baseline gap-2 p-2 bg-gray-200 rounded-lg shadow"
      data-testid="score-board"
    >
      <span className="font-bold">{kyokuStr}</span>
      <span className="text-sm">残り{wallCount}</span>
      <span className="text-sm">{honba}本場</span>
      <span className="text-sm flex items-center">
        供託
        <span data-testid="kyotaku" className="ml-1">
          {kyotaku}
        </span>
      </span>
    </div>
  );
};
